export default {
  'menu.login': 'Login',
  'menu.register': 'Register',
  'menu.register-result': 'Register Result',
  'menu.dashboard': 'Dashboard',

  'menu.dashboard.workplace': 'Workplace',
  'menu.exception.403': '403',
  'menu.exception.404': '404',
  'menu.exception.500': '500',

  'menu.result': 'Result',
  'menu.result.success': 'Success',
  'menu.result.fail': 'Fail',
  'menu.exception': 'Exception',
  'menu.exception.not-permission': '403',
  'menu.exception.not-find': '404',
  'menu.exception.server-error': '500',
  'menu.exception.trigger': 'Trigger',
  'menu.account': 'Account',
  'menu.account.center': 'Account Center',
  'menu.account.settings': 'Account Settings',
  'menu.account.qualification': 'Qualification',
  'menu.account.trigger': 'Trigger Error',
  'menu.account.logout': 'Logout',

  //新增菜单
  //设计下单
  'menu.design-order': 'Design Order',
  'menu.design-order.drawing-order': 'Drawing Order',
  'menu.design-order.create-order-step-form': 'Pricing/Ordering',
  //系统管理
  'menu.system': 'System Management',
  'menu.system.user-list': 'User List',
  'menu.system.role-list': 'Role List',
  'menu.system.organization': 'Organization List',
  'menu.system.tenant': 'Tenant List',
  'menu.system.audit-log': 'Audit Log',
  //产品管理
  'menu.product': 'Product Management',
  'menu.product.product-list': 'Product List',
  'menu.product.my-module-library': 'My Module Library',
  'menu.product.mesa-module': 'Countertop Module Library',
  'menu.product.edge-library': 'Edge Library',
  'menu.product.rear-retaining-reservoir': 'Rear Retaining Reservoir',
  'menu.product.sink-storage': 'Sink Storage',
  'menu.product.batten-store': 'Batten Store',
  'menu.product.tap-room': 'Tap Room',
  'menu.product.cook-house': 'Cookhouse',
  //售后服务
  'menu.after-sales-service': 'After-Sales Service',
  'menu.after-sales-service.order-complaint': 'Order Complaint',
  'menu.after-sales-service.order-list': 'Order List',
  'menu.after-sales-service.after-sales-order': 'After-Sales Order',
  'menu.after-sales-service.after-sales-order-details': 'After-Sales Order Details',
  'menu.after-sales-service.personnel-complaint': 'Personnel Complaint',

  //物流
  'menu.logistics': 'Logistics',
  'menu.logistics.logistics-prices': 'Logistics Prices',
  'menu.logistics.prices-record': 'Prices Record',

  //收发货管理
  'menu.receive-delivery': 'Receive and Delivery Management',
  'menu.receive-delivery.dispatch-bill': 'Dispatch Bill',
  'menu.receive-delivery.new-dispatch-bill': 'New Dispatch Bill',
  'menu.receive-delivery.scan-sign-for': 'Scan and Sign for',
  'menu.receive-delivery.sign-record': 'Sign Record',
  'menu.receive-delivery.scan-quality-testing': 'Scan and Quality Testing',
  'menu.receive-delivery.quality-testing-record': 'Quality Testing Record',
  'menu.receive-delivery.scan-put-in': 'Scan and Put In',
  'menu.receive-delivery.put-in-record': 'Put-In Record',

  //企业
  'menu.corporate': 'Employee Management',
  //一站式加工
  'menu.order': 'One-Stop Processing',
  'menu.order.create-order-step-form': 'Pricing/Ordering',
  'menu.order.store-order': 'Store Order',
  'menu.order.factory-order-receive': 'Factory Order Receive',
  'menu.order.factory-order': 'Factory Work Order',
  'menu.order.complaint-list': 'Complaint List',
  'menu.order.opti-para-configuration': 'Layout Optimization Configuration',
  'menu.order.store-order-details': 'Order Details',
  'menu.order.order-evaluation': 'View Evaluation',

  'menu.order.file-history-list': 'Pricing/Ordering',

  'menu.production-plan': 'Production Management',
  'menu.production-plan.generate-plan': 'Generate Production Plan',
  'menu.production-plan.view-plan': 'View Production Plan',
  'menu.production-plan.generate-receipt': 'Generate Material Requisition',
  'menu.production-plan.view-receipt': 'View Material Requisition',
  'menu.production-plan.work-order': 'Production Line Work Order Management',
  'menu.production-plan.arrange-calendar': 'Scheduling Calendar',
  'menu.production-plan.real-time-board': 'Real-Time Production Dashboard',

  'menu.production-plan.capacity': 'View Production Capacity',
  'menu.production-plan.record': 'Update Records',
  'menu.order.payment-order': 'Order Payment',
  'menu.order.payment-order-result': 'Payment Result',

  //配件库管理
  'menu.parts': 'Parts Inventory Management',
  'menu.parts.parts-post': 'Parts Shipment',
  'menu.parts.parts-depot': 'Parts Depot',
  'menu.parts.parts-confirm': 'Parts Shipment Confirmation List',

  'menu.group-order': 'Group Order',
  'menu.group-order.store-order': 'Store Order',
  'menu.group-order.order-batch': 'Order Batch',
  'menu.group-order.typography-optimization': 'Typography Optimization',
  'menu.group-order.store-order-details': 'Order Details',
  'menu.group-order.factory-order-details': 'Work Order Details',

  //
  'menu.wallet': 'Prepaid Account',
  'menu.wallet.transfer-in': 'Offline Transfer',
  'menu.wallet.balance': 'Wallet',
  'menu.wallet.transfer-in-record': 'Transfer In Record',

  'menu.wallet.offline-recharge': 'Offline Recharge',
  'menu.wallet.cash-account': 'Cash Account',
  'menu.wallet.pay-rank': 'Recharge Record',
  'menu.wallet.transaction-detail': 'Transaction Details',
  'menu.wallet.record-withdrawal': 'Withdrawal Record',
  'menu.wallet.supplement-record': 'Supplement Record',
  'menu.wallet.pay-set': 'Payment Settings',
  'menu.wallet.transfer-out': 'Transfer Out Request',
  //
  'menu.invoice': 'Invoicing Center',
  'menu.invoice.request-invoice': 'Invoice Request',
  'menu.invoice.again-invoice': 'Reissue Invoice',
  'menu.invoice.plain-invoice-details': 'Plain Invoice Details',
  'menu.invoice.vat-invoice-details': 'VAT Invoice Details',
  'menu.invoice.merge-invoice-details': 'Merged Invoice Details',
  'menu.invoice.again-plain-invoice': 'Reissue Plain Invoice',
  'menu.invoice.again-vat-invoice': 'Reissue VAT Invoice',
  'menu.invoice.again-merge-invoice': 'Reissue Merged Invoice',
  'menu.invoice.drawings-apply': 'Payment Request',
  'menu.invoice.drawings-record': 'Payment Record',

  // 物料管理
  'menu.invoice.drawings-confirm': 'Payment Details',
  // Material Management
  'menu.material': 'Material Management',
  'menu.material.material-stock': 'Material Stock',
  'menu.material.put-in-material': 'Inventory Management',
  'menu.material.put-in-record': 'Inventory Record',
  'menu.material.let-out-material': 'Outbound Management',
  'menu.material.let-out-record': 'Outbound Record',
  'menu.material.material-category': 'Material Category Configuration',
  'menu.material.related-products': 'Related Products',

  //
  'menu.processingManagement': 'Processing Management',
  'menu.processingManagement.craft-quote': 'Craft Quotation',
  'menu.processingManagement.installation-quotation': 'Installation Quotation',
  'menu.workflow': 'Workflow',
  'menu.feedback': 'Feedback',
  'menu.feedback.complaint': 'Service Complaint',
  'menu.feedback.internal-test': 'Internal Test Feedback',
  'menu.public-management': 'Public Management',
  'menu.production-line': 'Production Line Management',
  'menu.production-line.production-line-config': 'Multiple Production Line Configuration',
  'menu.production-line.device-list': 'Device Management Configuration',
  'menu.production-line.device-edit': 'Device Editing',
  'menu.production-line.device-add': 'Add Device',
};
