export default {
  'menu.login': '登录',
  'menu.register': '注册',
  'menu.register-result': '注册结果',
  'menu.reset-password': '重置密码',
  'menu.forget-password': '忘记密码',
  'menu.reset-confirm-email': '确认激活邮件',
  'menu.dashboard': '工作台',

  'menu.dashboard.workplace': '桌面',
  'menu.exception.403': '403',
  'menu.exception.404': '404',
  'menu.exception.500': '500',

  'menu.result': '结果页',
  'menu.result.success': '成功页',
  'menu.result.fail': '失败页',
  'menu.exception': '异常页',
  'menu.exception.not-permission': '403',
  'menu.exception.not-find': '404',
  'menu.exception.server-error': '500',
  'menu.exception.trigger': '触发错误',
  'menu.account': '个人页',
  'menu.account.center': '个人中心',
  'menu.account.settings': '个人设置',
  'menu.account.qualification': '资质认证',
  'menu.account.bank-card': '银行卡包',

  'menu.account.trigger': '触发报错',
  'menu.account.logout': '退出登录',

  //新增菜单
  //设计下单
  'menu.design-order': '设计下单',
  'menu.design-order.drawing-order': '绘图下单',
  'menu.design-order.create-order-step-form': '计价/下单',
  //系统管理
  'menu.system': '系统管理',
  'menu.system.user-list': '用户列表',
  'menu.system.role-list': '角色列表',
  'menu.system.organization': '组织列表',
  'menu.system.tenant': '租户列表',
  'menu.system.audit-log': '审计日志',
  //产品管理
  'menu.product': '产品管理',
  'menu.product.product-list': '产品列表',
  'menu.product.my-module-library': '我的方案库',
  'menu.product.mesa-module': '台面模块库',
  'menu.product.edge-library': '边形库',
  'menu.product.rear-retaining-reservoir': '后挡水库',
  'menu.product.sink-storage': '水槽库',
  'menu.product.batten-store': '垫条库',
  'menu.product.tap-room': '龙头库',
  'menu.product.cook-house': '炉灶库',
  //售后服务
  'menu.after-sales-service': '售后服务',
  'menu.after-sales-service.order-complaint': '订单投诉',
  'menu.after-sales-service.order-list': '订单列表',
  'menu.after-sales-service.after-sales-order': '售后单',
  'menu.after-sales-service.after-sales-order-details': '售后单详情',
  'menu.after-sales-service.personnel-complaint': '投诉工作人员',

  //物流
  'menu.logistics': '物流',
  'menu.logistics.logistics-prices': '物流报价',
  'menu.logistics.prices-record': '报价记录',

  //收发货管理
  'menu.receive-delivery': '收发货管理',
  'menu.receive-delivery.dispatch-bill': '发货通知单',
  'menu.receive-delivery.new-dispatch-bill': '新建发货单',
  'menu.receive-delivery.scan-sign-for': '扫码签收',
  'menu.receive-delivery.sign-record': '签收记录',
  'menu.receive-delivery.scan-quality-testing': '扫码质检',
  'menu.receive-delivery.quality-testing-record': '质检记录',
  'menu.receive-delivery.scan-put-in': '扫码入库',
  'menu.receive-delivery.put-in-record': '入库记录',

  //企业
  'menu.corporate': '员工管理',
  //一站式加工
  'menu.order': '一站式加工',
  'menu.order.create-order-step-form': '计价/下单',
  'menu.order.store-order': '门店订单',
  'menu.order.factory-order-receive': '工厂接单',
  'menu.order.factory-order': '工厂工单',
  'menu.order.complaint-list': '投诉列表',
  'menu.order.opti-para-configuration': '排版优化配置',
  'menu.order.store-order-details': '订单详情',
  'menu.order.order-evaluation': '查看评价',

  'menu.order.file-history-list': '计价/下单',

  'menu.production-plan': '生产管理',
  'menu.production-plan.generate-plan': '生成生产计划',
  'menu.production-plan.view-plan': '查看生产计划',
  'menu.production-plan.generate-receipt': '生成领料单',
  'menu.production-plan.view-receipt': '查看领料单',
  'menu.production-plan.work-order': '产线工单管理',
  'menu.production-plan.arrange-calendar': '排产日历',
  'menu.production-plan.real-time-board': '生产实时看板',

  'menu.production-plan.capacity': '查看产能',
  'menu.production-plan.record': '更新记录',
  'menu.order.payment-order': '订单支付',
  'menu.order.payment-order-result': '支付结果',

  //配件库管理
  'menu.parts': '配件库管理',
  'menu.parts.parts-post': '邮寄配件',
  'menu.parts.parts-depot': '配件库',
  'menu.parts.parts-confirm': '配件邮寄确认清单',

  'menu.group-order': '集团订单',
  'menu.group-order.store-order': '门店订单',
  'menu.group-order.order-batch': '订单合批',
  'menu.group-order.typography-optimization': '排版优化',
  'menu.group-order.store-order-details': '订单详情',
  'menu.group-order.factory-order-details': '工单详情',

  //
  'menu.wallet': '预付款账户',
  'menu.wallet.transfer-in': '线下转入',
  'menu.wallet.balance': '钱包',
  'menu.wallet.transfer-in-record': '转入记录',

  'menu.wallet.offline-recharge': '线下充值',
  'menu.wallet.cash-account': '现金账户',
  'menu.wallet.pay-rank': '充值记录',
  'menu.wallet.transaction-detail': '交易明细',
  'menu.wallet.record-withdrawal': '提现记录',
  'menu.wallet.supplement-record': '补款记录',
  'menu.wallet.pay-set': '支付设置',
  'menu.wallet.transfer-out': '转出申请',
  //
  'menu.invoice': '开票中心',
  'menu.invoice.request-invoice': '通知开票',
  'menu.invoice.again-invoice': '补开发票',
  'menu.invoice.plain-invoice-details': '普通发票详情',
  'menu.invoice.vat-invoice-details': '增值税发票详情',
  'menu.invoice.merge-invoice-details': '合并开票详情',
  'menu.invoice.again-plain-invoice': '补开普通发票',
  'menu.invoice.again-vat-invoice': '补开增值税发票',
  'menu.invoice.again-merge-invoice': '补开合并开票',
  'menu.invoice.drawings-apply': '打款申请',
  'menu.invoice.drawings-record': '打款记录',
  'menu.invoice.drawings-confirm': '打款详情',
  // 物料管理
  'menu.material': '物料管理',
  'menu.material.material-stock': '物料库存',
  'menu.material.put-in-material': '入库管理',
  'menu.material.put-in-record': '入库记录',
  'menu.material.let-out-material': '出库管理',
  'menu.material.let-out-record': '出库记录',
  'menu.material.material-category': '物料类别配置',
  'menu.material.related-products': '关联产品',

  //
  'menu.processingManagement': '加工管理',
  'menu.processingManagement.craft-quote': '工艺报价',
  'menu.processingManagement.installation-quotation': '安装报价',
  'menu.workflow': '工作流',
  'menu.feedback': '反馈',
  'menu.feedback.complaint': '服务投诉',
  'menu.feedback.internal-test': '内测反馈',
  'menu.public-management': '公共管理',
  'menu.production-line': '产线管理',
  'menu.production-line.production-line-config': '多产线配置',
  'menu.production-line.device-list': '设备管理配置',
  'menu.production-line.device-edit': '设备编辑',
  'menu.production-line.device-add': '添加设备',
};
